<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <ProduceReferenceAssemblyInOutDir>true</ProduceReferenceAssemblyInOutDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="Syncfusion.Licensing" Version="27.2.2" />
    <PackageReference Include="Syncfusion.Xamarin.SfChart" Version="27.2.2" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2662" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.8.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Views\AddSets.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Views\Page1.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\HomePage.xaml.cs">
      <DependentUpon>HomePage.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Profile.xaml.cs">
      <DependentUpon>Profile.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\LogRoutine.xaml.cs">
      <DependentUpon>LogRoutine.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\EditRoutine.xaml.cs">
      <DependentUpon>EditRoutine.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Xcises.xaml.cs">
      <DependentUpon>Xcises.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Routines.xaml.cs">
      <DependentUpon>Routines.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Stats.xaml.cs">
      <DependentUpon>Stats.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>